language: scala
scala:
  - 2.10.4
  - 2.11.6
jdk:
  - openjdk7
  - openjdk6
sudo: false
cache:
  directories:
      - $HOME/.ivy2
script:
  - sbt -jvm-opts travis/jvmopts.test clean coverage test
  - sbt -jvm-opts travis/jvmopts.test scalastyle
after_success:
  - sbt coveralls
